<Project>
  <PropertyGroup>
    <!-- Enable central package management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Npgsql" Version="8.0.9" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="MySqlConnector" Version="2.2.6" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageVersion Include="Azure.Core" Version="1.62.0" />
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="Batec.Azure.Data.Extensions.MySqlConnector" Version="1.0.0" />
    <PackageVersion Include="Batec.Azure.Data.Extensions.Npgsql" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup Condition="('$(IsTestProject)' == 'true') OR ('$(IsTestSupportProject)' == 'true') OR ('$(IsPerfProject)' == 'true') OR ('$(IsStressProject)' == 'true') OR ('$(IsSampleProject)' == 'true')">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NUnit" Version="3.13.3" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
  </ItemGroup>
</Project>