<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestSupportProject>true</IsTestSupportProject>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworks>$(RequiredTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="Azure.Core" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

</Project>
