name: CI

on: [push]

permissions:
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        environment:
          name: staging
        env:
            PACKAGE_VERSION: 1.0.0-beta.1
    
        steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: |
                6.0.x
                7.0.x
        - name: Pack MySqlConnector Extension
          working-directory: ./Batec.Azure.Data.Extensions.MySqlConnector/src
          run: dotnet pack -c Release -o ./../../artifacts/   
        - name: Pack Npgsql Extension
          working-directory: ./Batec.Azure.Data.Extensions.Npgsql/src
          run: dotnet pack -c Release -o ./../../artifacts/
        - name: Restore Solution
          run: dotnet restore -s ./artifacts/ -s https://api.nuget.org/v3/index.json Batec.Azure.Data.Extensions.sln  
        - name: Build
          run: dotnet build --no-restore Batec.Azure.Data.Extensions.sln
        - name: Azure CLI Login
          uses: azure/login@v1
          with:
            client-id: ${{  secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Test Common
          working-directory: ./Batec.Azure.Data.Extensions.Common/tests/
          run: dotnet test