name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        PACKAGE_VERSION: 1.0.0-beta.1

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Authenticate nuget
      run: dotnet nuget add source --username felipmiguel --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/felipmiguel/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
    - name: Package Core
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: Microsoft.Azure.Data.Extensions.Core
    - name: Publish Core
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.Core/bin/Release/Microsoft.Azure.Data.Extensions.Core.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package Npgsql
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: Microsoft.Azure.Data.Extensions.Npgsql
    - name: Publish Npgsql
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.Npgsql/bin/Release/Microsoft.Azure.Data.Extensions.Npgsql.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package Postgres EF Core
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: Microsoft.Azure.Data.Extensions.Npgsql.EntityFrameworkCore
    - name: Publish Postgresql EF Core
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.Npgsql.EntityFrameworkCore/bin/Release/Microsoft.Azure.Data.Extensions.Npgsql.EntityFrameworkCore.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package MySql
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: Microsoft.Azure.Data.Extensions.MySql    
    - name: Publish MySql
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.MySql/bin/Release/Microsoft.Azure.Data.Extensions.MySql.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      
    - name: Package MySql EF Core
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: Microsoft.Azure.Data.Extensions.MySql.EntityFrameworkCore    
    - name: Publish MySql EF Core
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.MySql.EntityFrameworkCore/bin/Release/Microsoft.Azure.Data.Extensions.MySql.EntityFrameworkCore.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package MySqlConnector
      run: dotnet pack --no-restore --configuration 'Release' -p -p:Version=$PACKAGE_VERSION
      working-directory: Microsoft.Azure.Data.Extensions.MySqlConnector    
    - name: Publish MySqlConnector
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.MySqlConnector/bin/Release/Microsoft.Azure.Data.Extensions.MySqlConnector.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
     
    - name: Package MySqlConnector EF Core
      run: dotnet pack --no-restore --configuration 'Release' -p -p:Version=$PACKAGE_VERSION
      working-directory:Microsoft.Azure.Data.Extensions.Pomelo.EntityFrameworkCore    
    - name: Publish MySqlConnector EF Core
      run: dotnet nuget push "Microsoft.Azure.Data.Extensions.Pomelo.EntityFrameworkCore/bin/Release/Microsoft.Azure.Data.Extensions.Pomelo.EntityFrameworkCore.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate