name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        PACKAGE_VERSION: 1.0.0-beta.1

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Authenticate nuget
      run: dotnet nuget add source --username felipmiguel --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/felipmiguel/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
    - name: Package Core
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.Core
    - name: Publish Core
      run: dotnet nuget push "AzureDb.Passwordless.Core/bin/Release/AzureDb.Passwordless.Core.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package Postgres
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.Postgresql
    - name: Publish Postgresql
      run: dotnet nuget push "AzureDb.Passwordless.Postgresql/bin/Release/AzureDb.Passwordless.Postgresql.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package Postgres EF Core
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.Postgresql.EntityFrameworkCore
    - name: Publish Postgresql EF Core
      run: dotnet nuget push "AzureDb.Passwordless.Postgresql.EntityFrameworkCore/bin/Release/AzureDb.Passwordless.Postgresql.EntityFrameworkCore.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package MySql
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.MySql    
    - name: Publish MySql
      run: dotnet nuget push "AzureDb.Passwordless.MySql/bin/Release/AzureDb.Passwordless.MySql.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      
    - name: Package MySql EF Core
      run: dotnet pack --no-restore --configuration 'Release' -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.MySql.EntityFrameworkCore    
    - name: Publish MySql EF Core
      run: dotnet nuget push "AzureDb.Passwordless.MySql.EntityFrameworkCore/bin/Release/AzureDb.Passwordless.MySql.EntityFrameworkCore.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    
    - name: Package MySqlConnector
      run: dotnet pack --no-restore --configuration 'Release' -p -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.MySqlConnector    
    - name: Publish MySqlConnector
      run: dotnet nuget push "AzureDb.Passwordless.MySqlConnector/bin/Release/AzureDb.Passwordless.MySqlConnector.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
     
    - name: Package MySqlConnector EF Core
      run: dotnet pack --no-restore --configuration 'Release' -p -p:Version=$PACKAGE_VERSION
      working-directory: AzureDb.Passwordless.MySqlConnector.EntityFrameworkCore    
    - name: Publish MySqlConnector EF Core
      run: dotnet nuget push "AzureDb.Passwordless.MySqlConnector.EntityFrameworkCore/bin/Release/AzureDb.Passwordless.MySqlConnector.EntityFrameworkCore.${PACKAGE_VERSION}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
