name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Authenticate nuget
      run: dotnet nuget add source --username felipmiguel --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/felipmiguel/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package Postgres
      run: dotnet pack --no-restore --configuration 'Release'
      working-directory: AzureDb.Passwordless.Postgresql
    - name: Publish Postgresql
      run: dotnet nuget push "AzureDb.Passwordless.Postgresql/bin/Release/AzureDb.Passwordless.Postgresql.1.0.0.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Package MySql
      run: dotnet pack --no-restore --configuration 'Release'
      working-directory: AzureDb.Passwordless.MySql    
    - name: Publish MySql
      run: dotnet nuget push "AzureDb.Passwordless.MySql/bin/Release/AzureDb.Passwordless.MySql.1.0.0.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
