name: Release

on:
    release:
        types: published

jobs:
    package:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            dotnet-version: [ '7.0.x', '6.0.x' ]
      env:
        PACKAGE_VERSION: ${{ github.event.release.tag_name }}
    
      steps:
      - uses: actions/checkout@v3
      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
    
      - name: Package MySqlConnector
        working-directory: ./Batec.Azure.Data.Extensions.MySqlConnector/src
        run: dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../package
    
      - name: Package Pomelo.EntityFrameworkCore.MySql
        working-directory: ./Batec.Azure.Data.Extensions.Pomelo.EntityFrameworkCore/src
        run: dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../package
    
      - name: Package MySqlConnector
        working-directory: ./Batec.Azure.Data.Extensions.MySqlConnector/src
        run: dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../package

      - name: Package Pomelo.EntityFrameworkCore.MySql
        working-directory: ./Batec.Azure.Data.Extensions.Pomelo.EntityFrameworkCore/src -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../package
        run: dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }}

      
      