name: Release

on:
    release:
        types: published

jobs:
    package:
      runs-on: ubuntu-latest
      environment: nuget
      strategy:
        matrix:
            dotnet-version: [ '7.0.x', '6.0.x' ]
      env:
        PACKAGE_VERSION: ${{ github.event.release.tag_name }}
    
      steps:
      - uses: actions/checkout@v3
      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
    
      - name: Package MySqlConnector
        working-directory: ./Batec.Azure.Data.Extensions.MySqlConnector/src
        run: dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../../package
    
      - name: Package Npgsql
        working-directory: ./Batec.Azure.Data.Extensions.MySqlConnector/src
        run: dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../../package
        

      - name: Package Pomelo.EntityFrameworkCore
        working-directory: ./Batec.Azure.Data.Extensions.Pomelo.EntityFrameworkCore/src
        run: |
            dotnet restore -s ../../package -s https://api.nuget.org/v3/index.json
            dotnet pack --no-restore -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../../package

      - name: Package Npgsql.EntityFrameworkCore
        working-directory: ./Batec.Azure.Data.Extensions.Npgsql.EntityFrameworkCore/src
        run: |
            dotnet restore -s ../../package -s https://api.nuget.org/v3/index.json
            dotnet pack -c Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ../../package
      
      - name: Publish MySqlConnector
        working-directory: ./package
        run: dotnet nuget publish --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json ./Batec.Azure.Data.Extensions.MySqlConnector.${{ env.PACKAGE_VERSION }}.nupkg
    
      - name: Publish Npgsql
        working-directory: ./package
        run: dotnet nuget publish --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json ./Batec.Azure.Data.Extensions.Npgsql.${{ env.PACKAGE_VERSION }}.nupkg
        
      - name: Publish Pomelo.EntityFrameworkCore
        working-directory: ./package
        run: dotnet nuget publish --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json ./Batec.Azure.Data.Extensions.Pomelo.EntityFrameworkCore.${{ env.PACKAGE_VERSION }}.nupkg

      - name: Publish Npgsql.EntityFrameworkCore
        working-directory: ./package
        run: dotnet nuget publish --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json ./Batec.Azure.Data.Extensions.Npgsql.EntityFrameworkCore.${{ env.PACKAGE_VERSION }}.nupkg

      
      